export const PROVIDER_MODELS: Record<string, string[]> = {
  claude:       ["claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5-20251001"],
  gemini:       ["gemini-2.5-pro-preview", "gemini-2.0-flash", "gemini-1.5-pro"],
  codex:        ["codex-1", "codex-1-mini", "gpt-4.5", "gpt-4o"],
  openai:       ["gpt-4.5", "gpt-4o", "gpt-4o-mini", "o4-mini", "o3"],
  deepseek:     ["deepseek-chat", "deepseek-reasoner"],
  groq:         ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
  openrouter:   ["openai/gpt-4o", "anthropic/claude-sonnet-4-6", "google/gemini-2.5-pro", "meta-llama/llama-4-maverick"],
  xai:          ["grok-3-latest", "grok-3-mini", "grok-2-latest"],
  mistral:      ["mistral-large-latest", "mistral-medium-latest", "mistral-small-latest", "codestral-latest"],
  perplexity:   ["llama-3.1-sonar-large-128k-online", "llama-3.1-sonar-small-128k-online"],
  together:     ["meta-llama/Llama-3-70b-chat-hf", "mistralai/Mixtral-8x7B-Instruct-v0.1"],
  cerebras:     ["llama3.1-70b", "llama3.1-8b"],
  fireworks:    ["accounts/fireworks/models/llama-v3p1-70b-instruct", "accounts/fireworks/models/mixtral-8x7b-instruct"],
  azure:        ["gpt-4o", "gpt-4-turbo", "gpt-35-turbo"],
  "opencode-zen": ["claude-sonnet-4-6", "claude-opus-4-7", "gpt-4o"],
  "opencode-go":  ["deepseek-v4-flash", "deepseek-v4-pro", "qwen3.5-plus", "qwen3.6-plus", "kimi-k2.5", "kimi-k2.6"],
  cohere:       ["command-r-plus", "command-r"],
  deepinfra:    ["meta-llama/Meta-Llama-3.1-70B-Instruct", "mistralai/Mixtral-8x7B-Instruct-v0.1"],
  moonshot:     ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
  minimax:      ["abab6.5s-chat", "abab5.5s-chat"],
  nvidia:       ["meta/llama-3.1-70b-instruct", "mistralai/mixtral-8x7b-instruct"],
  nebius:       ["meta-llama/Meta-Llama-3.1-70B-Instruct", "mistralai/Mixtral-8x7B-Instruct-v0.1"],
  huggingface:  ["meta-llama/Llama-3.1-70B-Instruct", "mistralai/Mixtral-8x7B-Instruct-v0.1"],
  ollama:       ["llama3.3", "llama3.1", "mistral", "codellama", "phi4", "gemma3", "qwen2.5"],
  sambanova:    ["Meta-Llama-3.3-70B-Instruct", "DeepSeek-V3.1", "Meta-Llama-3.1-8B-Instruct"],
  hyperbolic:   ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-72B-Instruct"],
  novita:       ["deepseek/deepseek-v3-0324", "qwen/qwen3-235b-a22b-instruct-2507", "meta-llama/llama-3.3-70b-instruct"],
  zhipu:        ["glm-4.6", "glm-4.5", "glm-4.5-air"],
  siliconflow:  ["deepseek-ai/DeepSeek-V3", "Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-R1"],
  "vercel-gateway": ["openai/gpt-4o", "anthropic/claude-sonnet-4-5", "xai/grok-4"],
  "github-models":  ["openai/gpt-4o", "openai/gpt-4o-mini", "deepseek/DeepSeek-R1"],
  chutes:       ["deepseek-ai/DeepSeek-V3-0324", "Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-R1"],
  writer:       ["palmyra-x5", "palmyra-x4"],
  ai21:         ["jamba-large", "jamba-mini"],
  upstage:      ["solar-pro2", "solar-pro", "solar-mini"],
  venice:       ["llama-3.3-70b", "deepseek-ai-DeepSeek-R1", "venice-uncensored"],
  baseten:      ["deepseek-ai/DeepSeek-V3-0324", "deepseek-ai/DeepSeek-R1", "meta-llama/Llama-3.3-70B-Instruct"],
  featherless:  ["Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V3", "meta-llama/Meta-Llama-3.1-8B-Instruct"],
  kluster:      ["deepseek-ai/DeepSeek-V3", "deepseek-ai/DeepSeek-R1", "klusterai/Meta-Llama-3.3-70B-Instruct-Turbo"],
  lambda:       ["deepseek-v3-0324", "deepseek-r1-671b", "llama-3.3-70b-instruct-fp8"],
  parasail:     ["deepseek-ai/DeepSeek-V3-0324", "deepseek-ai/DeepSeek-R1", "meta-llama/Llama-3.3-70B-Instruct"],
  friendli:     ["deepseek-ai/DeepSeek-R1", "meta-llama/Llama-3.3-70B-Instruct", "Qwen/Qwen3-235B-A22B"],
  "inference-net": ["deepseek-ai/deepseek-v3-0324", "meta-llama/llama-3.3-70b-instruct/fp-8", "deepseek-ai/deepseek-r1"],
  gmi:          ["deepseek-ai/DeepSeek-V3.1", "Qwen/Qwen3-235B-A22B", "meta-llama/Llama-3.3-70B-Instruct"],
  lmstudio:     [],
  custom:       [],
};
